name: SportsWarehouse

on: [push]

jobs:
  run-nba-database-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: d7nY06ZOoh1N8SCTB5SI
          MYSQL_DATABASE: bzynluexqfmjzzx56a06
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libmysqlclient-dev

      - name: Cache Pip Install
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run NBA Database Test
        run: |
          cd Test/
          pytest -v -s test.py || echo
